apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: content
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas
  resources:
    requests:
      storage: 50Gi
