apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      name: jackett
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          ports:
            - containerPort: 9117
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: jackett-config
              mountPath: /config
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads
        - name: jackett-config
          persistentVolumeClaim:
            claimName: jackett-config
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: content
spec:
  ports:
    - port: 9117
      protocol: TCP
      targetPort: 9117
  selector:
    app: jackett
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jackett
  namespace: default
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`jackett.local.tim.rip`)
      kind: Rule
      services:
        - name: jackett
          namespace: content
          port: 9117
  tls:
    certResolver: cloudflare
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: content
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
