apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: content
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas
  resources:
    requests:
      storage: 100Gi
