apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: freshtok-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      annotations:
        prometheus.io/port: "15692"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 15672
              name: management
            - containerPort: 5672
              name: amqp
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: freshtok-dev
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer
  loadBalancerIP: 10.69.4.131
  ports:
    - port: 15672
      name: management
    - port: 5672
      name: amqp
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: freshtok-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
