apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-binding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: jack-sa
    namespace: kube-system
  - kind: ServiceAccount
    name: eli-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
