apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github
  namespace: default
rules:
  - apiGroups: ["extensions", "apps", ""]
    resources: ["deployments","pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github
  namespace: default
subjects:
  - kind: ServiceAccount
    name: github-sa
    namespace: default
roleRef:
  kind: Role
  name: github
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-sa
  namespace: default
secrets:
  - name: github-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: github-sa
type: kubernetes.io/service-account-token

