apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      name: jellyfin
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          securityContext:
            privileged: true
          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: media-storage
              mountPath: /media
      volumes:
        - name: media-storage
          nfs:
            server: 10.69.1.5
            path: /mnt/NAS/nfs/vols/pvc-f6f7ffc5-2dc6-42a1-8b91-5109febbe768
        - name: jellyfin-config
          hostPath:
            path: /var/configs/jellyfin
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  ports:
    - port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app: jellyfin
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.local.tim.rip`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
