apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      name: jellyseerr
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr
          securityContext:
            privileged: true
          ports:
            - containerPort: 5055
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: jellyseerr-config
              mountPath: /app/config
      volumes:
        - name: jellyseerr-config
          hostPath:
            path: /var/configs/jellyseer
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: default
spec:
  ports:
    - port: 5055
      protocol: TCP
      targetPort: 5055
  selector:
    app: jellyseerr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.local.tim.rip`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
