apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nut
  template:
    metadata:
      name: nut
      annotations:
        prometheus.io/port: "9199"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/ups_metrics"
      labels:
        app: nut
    spec:
      containers:
        - name: nut
          image: ghcr.io/druggeri/nut_exporter:sha-0e74f70
          args: ['--nut.server', '10.69.1.4', '--nut.username', 'upsmon', '--nut.vars_enable', '']
          env:
            - name: NUT_EXPORTER_PASSWORD
              value: upsmanager
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
