apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      name: radarr
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 7878
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: media-storage
              mountPath: /movies
              subPath: movies
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: media-downloads
          hostPath:
            path: /var/mnt/storage/downloads
            type: DirectoryOrCreate
        - name: media-storage
          nfs:
            server: 10.69.1.5
            path: /mnt/NAS/nfs/vols/pvc-f6f7ffc5-2dc6-42a1-8b91-5109febbe768
        - name: radarr-config
          hostPath:
            path: /var/configs/radarr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
spec:
  ports:
    - port: 7878
      protocol: TCP
      targetPort: 7878
  selector:
    app: radarr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.local.tim.rip`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
