apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      name: sabnzbd
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: media-incomplete
              mountPath: /incomplete-downloads
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: media-downloads
          hostPath:
            path: /var/mnt/storage/downloads
            type: DirectoryOrCreate
        - name: media-incomplete
          emptyDir:
            sizeLimit: 250Gi
        - name: sabnzbd-config
          hostPath:
            path: /var/configs/sabnzbd
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sabnzbd
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.local.tim.rip`)
      kind: Rule
      services:
        - name: sabnzbd
          port: 8080
