apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      name: sonarr
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 8989
          resources:
            requests:
              cpu: "500m"
              memory: 500M
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media-storage
              mountPath: /tv
              subPath: tv
            - name: media-downloads
              mountPath: /downloads
      volumes:
        - name: media-downloads
          hostPath:
            path: /var/mnt/storage/downloads
            type: DirectoryOrCreate
        - name: media-storage
          nfs:
            server: 10.69.1.5
            path: /mnt/NAS/nfs/vols/pvc-f6f7ffc5-2dc6-42a1-8b91-5109febbe768
        - name: sonarr-config
          hostPath:
            path: /var/configs/sonarr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: default
spec:
  ports:
    - port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app: sonarr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.local.tim.rip`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
